### PR TITLE
Translation into Spanish of the documentation MuCow

### PR DESCRIPTION
**Pull request by leninalbertolp**
Translated to the Spanish master branch

### CODE REVIEW

**Comment by LoveAndCoding** [comment]
This converts the whole master branch to Spanish and gets rid of the English. This isn't quite the way we'll want to do this. Instead, we'll likely make a new folder for translations. At least, that's where I would lean.

**Comment by leninalbertolp** [comment]
Ho my God how much I'm sorry, I don't have much knowledge about how the Pull Request work thousand apology.

**Comment by LoveAndCoding** [comment]
It's no worries. No harm done. :) I've created a different pull request with the other change

**Comment by JeffryBooher** [comment]
@leninalbertolp I'm closing this pull request but feel free to put up a new one when you have fixed the

**Pull request closed without merging**
