### PR TITLE
Added an example for Content Tags inside parameters

### PR DESCRIPTION
**Pull request by LoveAndCoding**
Users on the forums were requesting clarification on this, so I added an example for it.

### CODE REVIEW

**Comment by JeffryBooher** [comment]
@ktsashes Thanks for the example. This is great!  Could you add a link in "08-Examples.md" with the rest of the example links?

**Comment by LoveAndCoding** [comment]
@JeffryBooher Sure, I can do that. Do you know, did @clabland ever track down the tool I used to generate the HTML files for the examples? The other links point to those rendered files which I haven't generated for this example. If he didn't, that's fine. I can either generate this one manually (it's very simple to do) or just point it to the raw .mucow file.

Also, the links in 08 probably need to be changed to link to the source files in the markdown, and then the renderer should convert the links when that's done. Probably requires lots of changes to FruitJS which I haven't done yet, including custom link altering and potentially plugins... :/ Just a thought.

**Comment by LoveAndCoding** [comment]
Nevermind, I recreated the tool. You can use the tool at https://github.com/WidgetsMu/Mucow-Example-Compiler to compile examples into HTML.

I mostly just copied what the old code did, so it's nothing fancy. Minor tweaks but that's about it. Probably do a pull request for the gh-pages branch in a bit

**Comment by LoveAndCoding** [comment]
Added the link to the 08-Examples page and pull request #15 adds the rendered HTML file to the site.

**Comment by JeffryBooher** [comment]
@ktsashes thanks for the updates!

**Pull request merged**
