### PR TITLE
Rendered Example Pages

### PR DESCRIPTION
**Pull request by LoveAndCoding**
Alright, let's try this again with the accidental inclusion of every check-in and file from the master branch, eh?

Rendered the example pages with the new tool. The new renders are live on [my version of the documentation here](http://widgetsmu.github.io/MuCowDocs/#hinteractive). And the tool is in [the Widgets.Mu repo](https://github.com/WidgetsMu/Mucow-Example-Compiler).

It may looks like a lot of change, but mostly it is just a difference in the renderer. I upgrade the highlighting code, and did some very minor tweaks to the style to make it look (and work) a bit nicer.

### CODE REVIEW

**Comment by LoveAndCoding** [comment]
I'll do a separate pull request with the new example MuCOW I created so that can all be done at once.

**Comment by JeffryBooher** [comment]
@clabland was in the process of getting this into an automated process.

**Comment by LoveAndCoding** [comment]
A much better way to go about things. Feel free to ignore this then. I'll assume you all found the tool then?

**Comment by JeffryBooher** [comment]
My thoughts were that you could work with him to get this automated. We should take this PR without objection.  I just wanted him to see it first in case there were any questions, etc...

**Comment by clabland** [comment]
This looks fine to me. 

From the automation standpoint, we need a way to run this new tool when .mucow files are committed, for example.

Never did find the tool, thanks for recreating it @ktsashes!

**Pull request merged**
